---
- include: preflight.yml
  tags:
    - ckb_preflight
    - ckb_setup
    - ckb_install
    - ckb_database
    - ckb_configure

- include: setup.yml
  become: true
  tags:
    - ckb_setup
    - ckb_install
    - ckb_database
    - ckb_configure

- include: install.yml
  become: true
  tags:
    - ckb_install

- include: configure.yml
  become: true
  tags:
    - ckb_configure

- include: database.yml
  become: true
  tags:
    - ckb_database

- include: status.yml
  tags:
    - ckb_status

- name: Restart CKB
  become: true
  meta: flush_handlers
  tags:
    - ckb_install
    - ckb_configure

- name: Stop CKB
  become: true
  service:
    name: "{{ ckb_service }}"
    state: stopped
  tags:
    - ckb_stop

- name: Restart CKB
  become: true
  service:
    name: "{{ ckb_service }}"
    state: restarted
  tags:
    - ckb_restart

- name: Start CKB
  become: true
  service:
    name: "{{ ckb_service }}"
    state: started
  tags:
    - ckb_start

- name: Wait For CKB RPC Service Launched
  wait_for:
    port: "{{ ckb_rpc_listen_address | regex_replace(\".*:\", \"\") }}"
  tags:
    - ckb_restart
    - ckb_start

- name: Stop CKB Miner
  become: true
  service:
    name: "{{ ckb_service }}-miner"
    state: stopped
  tags:
    - ckb_miner_stop

- name: Restart CKB Miner
  become: true
  service:
    name: "{{ ckb_service }}-miner"
    state: restarted
  tags:
    - ckb_miner_restart

- name: Start CKB Miner
  become: true
  service:
    name: "{{ ckb_service }}-miner"
    state: started
  tags:
    - ckb_miner_start
